# Generated by Django 4.1.4 on 2023-04-21 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Employer Name"),
                ),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="Enter the employer website URL",
                        null=True,
                        verbose_name="Employer Website",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployerContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Last Name"),
                ),
                (
                    "role",
                    models.CharField(max_length=100, verbose_name="Role (Position)"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "linkedin",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="LinkedIn Account",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Phone"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employer_contacts",
                        to="responses.employer",
                        verbose_name="Employer",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(max_length=100, verbose_name="Position Name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ThirdPartyCompany",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Company Name")),
                (
                    "website",
                    models.URLField(
                        blank=True,
                        help_text="Enter the third-party company website URL",
                        null=True,
                        verbose_name="Company Website",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ThirdPartyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Last Name"),
                ),
                (
                    "role",
                    models.CharField(max_length=100, verbose_name="Role (Position)"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "linkedin",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="LinkedIn Account",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Phone"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="thirdpartycontact_contacts",
                        to="responses.thirdpartycompany",
                        verbose_name="Third-Party Company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Response",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(auto_now_add=True, verbose_name="Response Date"),
                ),
                (
                    "status",
                    models.CharField(
                        help_text="Enter or update response status",
                        max_length=100,
                        verbose_name="Response Status",
                    ),
                ),
                (
                    "employer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employer_responses",
                        to="responses.employer",
                        verbose_name="Employer",
                    ),
                ),
                (
                    "employercontact",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employercontact_responses",
                        to="responses.employercontact",
                        verbose_name="Employer Contact",
                    ),
                ),
                (
                    "position",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="position_responses",
                        to="responses.position",
                        verbose_name="Position",
                    ),
                ),
                (
                    "thirdpartycontact",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="thirdpartycontact_responses",
                        to="responses.thirdpartycontact",
                        verbose_name="Third-Party Contact",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_responses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
        ),
    ]
