# Generated by Django 4.1.4 on 2023-02-15 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("responses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="response",
            name="company",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responses",
                to="responses.company",
                verbose_name="Компания",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="cv",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responses",
                to="responses.cv",
                verbose_name="Версия резюме",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="position",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responses",
                to="responses.position",
                verbose_name="Позиция",
            ),
        ),
        migrations.AlterField(
            model_name="response",
            name="template",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="responses",
                to="responses.template",
                verbose_name="Шаблон резюме",
            ),
        ),
    ]
