# Generated by Django 4.1.4 on 2022-12-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('responds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respond',
            name='letter',
            field=models.TextField(default='SOME STRING', max_length=500),
        ),
    ]
