# Generated by Django 4.1.4 on 2023-01-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("responds", "0002_respond_letter"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cv",
            name="name",
        ),
        migrations.RemoveField(
            model_name="position",
            name="name",
        ),
        migrations.AddField(
            model_name="company",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="company",
            name="slug",
            field=models.SlugField(
                default="SOME SLUG", max_length=200, verbose_name="Псевдоним"
            ),
        ),
        migrations.AddField(
            model_name="cv",
            name="slug",
            field=models.SlugField(
                default="SOME SLUG", max_length=200, verbose_name="Порядковый номер"
            ),
        ),
        migrations.AddField(
            model_name="cv",
            name="version",
            field=models.CharField(
                default="SOME VERSION", max_length=200, verbose_name="Версия резюме"
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
        migrations.AddField(
            model_name="position",
            name="position",
            field=models.CharField(
                default="SOME POSITION",
                max_length=200,
                verbose_name="Название позиции в вакансии",
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="slug",
            field=models.SlugField(
                default="SOME SLUG", max_length=200, verbose_name="Порядковый номер"
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="respond",
            name="letter",
            field=models.TextField(
                default="SOME STRING",
                max_length=500,
                verbose_name="Текст сопроводительного письма",
            ),
        ),
        migrations.AlterField(
            model_name="respond",
            name="resp_date",
            field=models.DateField(verbose_name="Дата отклика / отправки"),
        ),
        migrations.AlterField(
            model_name="template",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Шаблон резюме"),
        ),
    ]
